#!/bin/sh

echo "Configuring lower link Mesh IBSS network..."
iw dev wlan1 del
iw phy phy0 interface add mesh0 type ibss
ip link set up mtu 1532 dev mesh0
iw dev mesh0 ibss join Mesh 2412 HT20 fixed-freq 02:C0:FF:EE:BA:BE

echo "Adding lower link device to batman-adv..."
batctl if add mesh0
ip link set up dev bat0
